## Epithelial tissues

### What is an epithelial tissue? And what does it do?

Epithelial tissues are cell sheets with strong intercellular bonds that form physical barriers for major organs (lung, skin, intestine, etc.) It protects said organs from external physical, chemical, and microbial onslaughts. Besides protection, the main functions of epithelial cells include secretion, selective absorption, transcellular transport, and detection of sensation (Powell, D.W., 1981). It also plays a key role in developmental stages of by acting as growth support and driving critical shape changes. (Figure 1: Epithelial Caco2 cell monolayer labelled for a tight junction protein in blue and nuclei in red. CellBiol_MRCLMB)

### Physiological function in the body and polarity of the tissue

Epithelial cells are polarized, i.e., their apical side, facing the lumen of the organ, differs in shape and composition from the basolateral side. Its polar organization is reflected in the vectoral functions like transporting epithelia such as those of the renal tubule, absorptive epithelia such as those of the intestine, and secretory epithelial cells such as the hepatocytes are typical examples of epithelia that create and maintain concentration gradients between the separated compartments (Simons, K. and Fuller, S.D., 1985). In addition to this, polarized epithelia guide cell fate specification in development (Kim, E.J.Y., Korotkevich, E. and Hiiragi, T., 2018). (Figure 2: Polarized epithelia adapted from Chen, Jia, et al. 2018)

### Introduction to different components

Epithelial function primarily depends on tissue’s structure and microenvironment. It can be described completely in three parts: first cell structure; second cell connection; and lastly microenvironment.

#### Cell structure

In general, cell structure helps cells maintain the shape along with providing mechanical support to perform vital functions like division and migration. This structure is known as cell cytoskeleton. It includes different components, playing various roles together. For eukaryotic cells, it is constructed out of filamentous proteins to support the cell and its cytoplasmic constituents. There are three major filaments, which differ in size and protein. Microtubules are the largest type of filament of protein tubulin, with a diameter of about 25 nanometers (nm). Actin filaments are the smallest type, with a diameter of only about 6 nm. Finally, Intermediate filaments are mid-sized, with a diameter of about 10 nm. Unlike actin filaments and microtubules, intermediate filaments are constructed from several different subunit proteins. These filaments dynamically alter themselves in reaction to signals from microenvironments and cell networks (Alberts, B., et al., 2013; Fletcher, D.A. and Mullins, R.D., 2010). Mechanically, actin filaments are stiffer than microtubules in extension, but they rupture at lower extension. It is also reported that the intermediate filaments exhibit an intermediate extensional stiffness at lower extensions, but that the intermediate filament can sustain much larger extensions than the other two types of filaments while exhibiting a nonlinearly stiffening response (reference to the figure) (Janmey et al., 1991; Mofrad, M.R., 2009).
In case of epithelial layers, actin cytoskeleton in conjunction with intercellular junctions makes stronger cell-cell contacts and creates a tissue level integrity (Braga V. 2016). The perfect example of these tissue level structures can be seen in wound healing assays; where a wound is created in epithelial monolayer, and cells surrounding the wound create a ring of actin to close it (Brugués, A., et al., 2014). One must keep in mind that these structures tend to self-organize as well. It can be seen when cells are confined in a specific shape, like in case of circular islands of epithelial cells showed radial patterns in the actin organization (Jalal S., et al., 2019).

#### Description of cell-cell junctions

A multiple membrane-molecules can mediate adhesion between cells. One of these are cadherins, critical for epithelial cell cohesion through the formation of adherens junctions. In these junctions, cadherins are coupled to the cell cytoskeleton enabling force transmission between cells. It is finely regulated by both internal and external mechanisms. Desmosomes are another type of intercellular junction. They are coupled wit h intermediate filaments and the resulting supracellular network confers mechanical resilience on cell layers (Hatzfeld, M., Keil, R. & Magin, T. M. 2017; Latorre, E., et al., 2018). Tight junctions (TJ) perform a barrier function and enable the transport of ions across epithelial layers to be actively regulated. This plays an important role in the control of fluid pressures in tissues. Together, adherens junctions, desmosomes and tight junctions are the major mediators of epithelial cell–cell adhesion and their regulation enable emergent behaviors in cell sheets that are not observed in single-cell systems (Figure reference here) (Trepat, X. and Sahai, E., 2018; Ladoux, B. and Mège, R.M., 2017).

#### Extracellular matrix

The cell surroundings or a substrate on which cells are adhered on is called extracellular matrix (ECM); This substrate is interchangeably referred to as matrix/cellular microenvironment. ECM serves many functions: it endows a tissue with strength and resilience and thereby maintains its shape; it serves as a biologically active scaffolding on which cells can migrate or adhere; it helps to regulate the phenotype of the cells; it serves as an anchor for many substances including growth factors, proteases and inhibitors of such; and finally, it provides an aqueous environment for the diffusion of nutrients, ions, hormones and metabolites between the cell and the capillary network. On top of that it is subjected to mechanical forces such as blood flow in endothelia, air flow in respiratory epithelia or hydrostatic pressure in the mammary gland and bladder (Roca-Cusachs, P., Conte, V. & Trepat, X. 2017; Humphrey, J. D., et al., 2015; Waters, C. M., Roan, E. & Navajas, D., 2012; Paszek, M. J. & Weaver, V. M. 2004; Bross, S., et al., 2003). In many respects, therefore, it is the ECM that regulates cell shape, orientation, movement and overall function.
Cells and ECM have a symbiotic relationship between each other from signalling cues to various sensors on the cell surface. These cues are primarily sensed using integrins and focal adhesion complex in cell-substrate adhesion (Kechagia, J.Z., Ivaska, J. and Roca-Cusachs, P., 2019).  (Figure reference) Thus, triggering complex molecular processes which are required to maintain homeostasis and strongly affect processes in development or tumorigenesis (DuFort, C. C., Paszek, M. J. & Weaver, V. M. 2011; Northey, J. J., Przybyla, L. & Weaver, V. M. 2017).
ECM is a fibrous network of proteins, from mechanical perspective, the three primary structural constituents of the ECM are typically collagen (the most abundant protein in the body), elastin (the most elastic and chemically stable protein) and the proteoglycans (which often sequester significant water as well as growth factors, proteases, etc.). Due to its water content, deformation of ECM can produce cracks in epithelial layers. ECM acts as a poroelastic material soaking water upon stretch (like sponge) and releasing it under compression causing hydraulic fracture effect (Casares, L., et al, 2015). Moreover, collagen remodels itself under influence of cells aiding in migration or under stress (Shields, M. A., et al., 2012; Humphrey J D, 2003).
Like most of the cytoskeletal proteins, most extracellular components turnover continuously, albeit some very slowly. For example, collagen in the peridontal ligament appears to have a half-life of the order of days, whereas that in the vasculature may have a normal half-life of months. In response to altered loads, disease or injury, however, the rates of synthesis and degradation of collagen can increase many folds to have a rapid response (Humphrey J D, 2003).

### Epithelial Homeostasis

Epithelial integrity and homeostasis are of central importance to survival, and mechanisms have evolved to ensure these processes are maintained during growth and in response to damage (Macara, I.G., et al., 2014). For example, epithelial cells have one of the fastest turning over rates in the body. The entire gut cell lining turns over in 3-4 days. This turn over implies constant cell division and death. The excessive rate of division than the death may give rise to tumors. It is known that 90% of cancers emerge in simple epithelia (Torras, N. et al. 2018; Eisenhoffer, G.T. and Rosenblatt, J., 2013). Not only this but it could easily disrupt the barrier function as no gaps should emerge around dying or dividing cells. There is a spectrum of distinct disease states that have in common their effect of breaking down epithelial and/or endothelial barrier function.

#### Disease and Cancer from leaky barriers

If the fluid compartmentalization goes awry, it has profound implications for epithelial and stromal homeostasis, fluid and/or electrolyte balance, generation of inflammatory states, and even tumor microenvironment. There are number of bacterial toxins known to target junctions and cause alteration in TJ protein ZO1 which leads to compromised barrier function and causing pathologies like diarrhea and colitis (Fasano, A. et al. 1991). Cancer cells have tendency to spread and disperse metastatically, by using their very high rate of cell motility and diminished sense of cell adhesion. This elimination and/or reduction of TJ barriers in cancer are essential to allow metastatic cells to break in and out of blood vessels. Leaky barrier also allows a growing epithelial tumor an additional source of nutrients from luminal fluids (Mullin, J.M. et al., 2005).

#### Developmental disorders

Epithelia undergoes changes in shape with deformation and reorganization from embryo to adult stage. It is unsurprising that any improper function would lead to damage and disorder. Like in case of Epithelial–mesenchymal transition (EMT), a developmental process when epithelial cells gradually transform into mesenchymal-like cells by losing their epithelial functionality, which is involved in the pathogenesis of numerous lung diseases ranging from developmental disorders, fibrotic tissue remodeling to lung cancer. Another example, Bronchopulmonary dysplasia (BPD) is a chronic lung disease that occurs in very premature infants and is characterized by impaired alveologenesis and vascular development. BPD develops because of injury or infection on a very immature lung (Bartis, D. et al., 2014).

